### ISSUE TITLE
Use Sass Instead of Editing Compiled CSS

### ISSUE THREAD

**Issue by repository** [ToxxyTheTrash/SimplyDarkFuchsiaDarkness#1]
Figure out how to use sass, it will make your life so much easier. The compiler automatically fixes many problems for you. In addition, it will remove any redundant or useless rules. Currently, you are editing the compiled CSS files, which should not be edited manually. 

As for your issue with `@-moz-document domain("discordapp.com")`, please read [this.](https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix#CSS_prefixes) CSS rules with  prefix `-moz-` are only searched for by Mozilla browersers, so only Firefox and its forks. You will have to repeat this rule  manually and and all of its contents for each browser you would like to support. Again, here is a case where sass can simplify things. Sass compiler can automatically prefix rules that require them.

**Comment by ToxxyTheTrash** [comment]
thanks for this, will look into it

**Comment by ToxxyTheTrash** [comment]
right so to be clear, i wrote the usercss in stylus' usercss thingy itself. problem is it doesn't let me use anything aside ``moz-document``. i tried putting ``webkit`` instead of ``moz`` but since it returns with ``Unknown @ rule: @-webkit-document`` i cant save it. i'm fairly new to this and i don't know how to compile it since i've only been using prepros for ``.scss``. if you got the time, hmu on discord: toxxy the trash furry#5015
![image](https://user-images.githubusercontent.com/28952722/69009822-a7318080-0959-11ea-9401-dc87cf765e03.png)
here you can see me be a full retard in action ^

**Comment by repository** [comment]
Try using an editor other than whatever that is and then importing the CSS file. Also, `url-prefix("discordapp.com")` will not work as the URL will always start with the protocol, i.e. `https`. Stick to `domain("")`.

**Comment by repository** [comment]
Nevermind that, it seems that `@document` is only supported by Firefox, so it's reasonable that `@-webkit-document` is not recognized as a valid rule.

**Comment by ToxxyTheTrash** [comment]
![image](https://user-images.githubusercontent.com/28952722/69010055-c7623f00-095b-11ea-9189-1754d911a169.png)
ive just looked into it on notepad++ and somehow its "compiled" as domain already

**Comment by ToxxyTheTrash** [comment]
righty'o im still stuck with this and i don't know how to make it compatible for chrome properly. i'd really liek a response back and possibly a codeblock example of what i shoudl try using. this is honestly pissing me off due to how little to nothign there is info but only thing i found out about was this

![image](https://user-images.githubusercontent.com/28952722/69066780-3c984780-0a22-11ea-9dae-fb22142228df.png)

this however did not help me

**Comment by repository** [comment]
There seems to be no way of doing what you are looking for natively in CSS that is supported in all browers. Currently, the standard method of applying styles to a specific domain is by use of a userscript which inserts the CSS into the page.

**Comment by ToxxyTheTrash** [comment]
alrighty, thanks for the help anyways

**Comment by repository** [comment]
No problem, always glad to help.
