### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by sleighttt** [ToxxyTheTrash/SimplyDarkFuchsiaDarkness#4]
![image](https://user-images.githubusercontent.com/26939671/102560741-d26c2f00-4087-11eb-99d7-66aa0591590c.png)

This happens every time I type. Also, when you start up Discord, it does this, and you need to click a channel so it can fix itself.

**Comment by ToxxyTheTrash** [comment]
this is pretty much intentional since i don't exactly know how i'd make it work better; never bothered me in the first place. i also never had a problem with the chatbox being broken as soon as you start discord so i also can't do much about that.

if you have any possible ideas on workarounds, you're welcome to submit them as i'm not exactly sure on how i'd fix it.

**Comment by sleighttt** [comment]
When it starts up, the only workaround is to click on a channel, and it goes away. But for typing, I really have no idea.

**Comment by ToxxyTheTrash** [comment]
this will finally be implemented in the next update
